### ISSUE TITLE
influxdb 的时区怎么设置的？

### ISSUE THREAD

**Issue by Nymph-fan** [xtutu/influxdb-handbook#2]
官网没找到，我测试插入数据，时间比现在刚好早 8小时

**Comment by xtutu** [comment]
@Nymph-fan 
时间一般存的是一个整数类型，你存的多少，就是多少。  
只要你都是以国际标准时间来存储以及显示，或者都以utc8来存储与显示，就不会出现这个问题。  

具体的关系，可以看这篇文章：  
[http://xtutu.me/the-date-object-in-js/](http://xtutu.me/the-date-object-in-js/)

虽然是js写的，但是原理是一样的。

**Comment by ToView** [comment]
influxdb存储数据的时间是系统时区的UTC时间。假如东八区14:00插入数据，那么查出来的结果，time显示为6:00。

**Comment by yohhei** [comment]
好像目前还做不到

**Comment by xigang** [comment]
时间戳不需要设置，只要在查询的时设置时区就可以了。
eg:

```
SELECT mean("value") FROM "cpu" GROUP BY region, time(1d) fill(0) tz('America/Chicago')
```

**Comment by netyjq** [comment]
> 时间戳不需要设置，只要在查询的时设置时区就可以了。
> eg:
> 
> ```
> SELECT mean("value") FROM "cpu" GROUP BY region, time(1d) fill(0) tz('America/Chicago')
> ```

为什么我这样操作，没有效果

**Comment by diamondboy** [comment]
> > 时间戳不需要设置，只要在查询的时设置时区就可以了。
> > eg:
> > ```
> > SELECT mean("value") FROM "cpu" GROUP BY region, time(1d) fill(0) tz('America/Chicago')
> > ```
> 
> 为什么我这样操作，没有效果

因为influx是Go语言写的，如果你是windows平台下使用tz()无效，需要安装部署Go环境并且设置go的环境变量就可以了。
